import type { Metadata } from "next";
import { Roboto, Nunito } from "next/font/google";
import "../styles/globals.css"

import Navbar from "../components/Navbar";
import Footer from "../components/Footer"
import Hero from "../components/Hero"
import { useState } from "react";
import { AuthProvider } from "@/contexts/authContext";

const primaryFont = Nunito ({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-primary",
});

const secondaryFont = Roboto ({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-secondary",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html 
        lang="en"
        className={`${primaryFont.variable} ${secondaryFont.variable}`}>
        <body className={primaryFont.className}>
          <Navbar />
          <main className="container">{children}</main>
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
